<?php include('parts/header.php'); ?>
<?php include('parts/aside.php'); ?>
<?php include('parts/container.php'); ?>
<?php include('parts/games.php'); ?>
<?php include('parts/projects.php'); ?>
<?php include('parts/photography.php'); ?>
<?php include('parts/workplace.php'); ?>
<?php include('parts/culture.php'); ?>
<?php include('parts/footer.php'); ?>
